name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3", "8.4"]

    name: PHP ${{ matrix.php }} Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, zip
          tools: composer

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --ansi

      - name: Run syntax check
        run: find src -name "*.php" -exec php -l {} \;

      - name: Run basic test
        run: php test.php

      - name: Run PHPStan (if available)
        run: |
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse --no-progress
          else
            echo "PHPStan not available, skipping static analysis"
          fi

      - name: Run PHP CodeSniffer (if available)
        run: |
          if [ -f vendor/bin/phpcs ]; then
            vendor/bin/phpcs
          else
            echo "PHP CodeSniffer not available, skipping code style check"
          fi

      - name: Run PHPUnit tests (if available)
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "PHPUnit not available, skipping unit tests"
          fi
